### ISSUE TITLE
 `maid` tool not excluding specified files using `maid.json`

### ISSUE THREAD

**Issue by murtaza-nasir** [fsoft72/maid#1]
Hello!

I am using `maid` version `v0.3.6` to aggregate content from my project directories and files into a single Markdown file. However, I am encountering an issue where the tool is not excluding specified files as defined in the `maid.json` configuration file.

#### Steps to Reproduce

1. **Create `maid.json` in the Root Directory**:

    ```json
    {
      "patterns": [
        "src/app/legal/terms-of-service/page.tsx",
        "src/app/legal/privacy-policy/page.tsx",
        "src/app/legal/sla/page.tsx"
      ],
      "rules": []
    }
    ```

2. **Run the `maid` Command with `maid.json`**:

    ```bash
    maid -o output.md --maid-file maid.json --verbose src prisma next.config.ts tsconfig.json
    ```

3. **Run the `maid` Command with Direct Blacklist**:

    ```bash
    maid -o output.md --blacklist src/app/legal/terms-of-service/page.tsx --blacklist src/app/legal/privacy-policy/page.tsx --blacklist src/app/legal/sla/page.tsx --verbose src prisma next.config.ts tsconfig.json
    ```

4. **Check the Output**:

    The `output.md` file still includes the following files:
    - `src/app/legal/terms-of-service/page.tsx`
    - `src/app/legal/privacy-policy/page.tsx`
    - `src/app/legal/sla/page.tsx`

#### Expected Behavior

The specified files should be excluded from the `output.md` file.

#### Actual Behavior

The specified files are still being included in the `output.md` file.

#### Additional Information

- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10
- **Node.js Version**: 18.16.0
- **Project Structure**:
```
src/middleware.ts
src/types/*
src/app/layout.tsx
src/app/globals.css
src/app/page.tsx
src/app/logo.svg
src/app/favicon.ico
src/app/legal/*
src/app/profile/*
src/app/auth/*
src/app/prompt-management/*
src/app/api/auth/*
src/app/api/documents/*
src/app/api/generate-prompt/*
src/app/api/prompts/*
src/app/api/user/*
src/app/api/admin/*
src/app/components/ui/*
src/app/components/*
src/app/fonts/*
src/app/admin/*
src/lib/*
prisma/schema.prisma
prisma/migrations/*
next.config.ts
tsconfig.json
```

Thank you for your assistance!

**Comment by fsoft72** [comment]
Hello @murtaza-nasir  the `pattern` and `blacklist` parameters do not consider the whole path, but just the filename.
So, to blacklist your `page.tsx` you should specify only `page.tsx` in `patter` or `--blacklist` option (but this will exclude *all* `page.tsx` you could have in your project).

I am working on a modified version where it'll be possible to specify an exact file or directory with full path to exclude.

**Comment by fsoft72** [comment]
Hello @murtaza-nasir,  I have just released new maid `0.4.0`  that features a `.gitignore` similar syntax to exclude files and dirs.
Please, update and tell me if it works like expected. :smiley: 

Also, read the new README file, because there are some breaking changes

**Comment by murtaza-nasir** [comment]
@fsoft72 

Thank you for your help with this! I tried this. First I was getting an error with the package after updating it. 

``` bash
base) murtaza@aa:~/dir/app$ pip install fsoft_maid --upgrade
Requirement already satisfied: fsoft_maid in /home/murtaza/miniconda3/lib/python3.12/site-packages (0.3.6)
Collecting fsoft_maid
  Downloading fsoft_maid-0.4.0-py3-none-any.whl.metadata (8.0 kB)
Downloading fsoft_maid-0.4.0-py3-none-any.whl (9.5 kB)
Installing collected packages: fsoft_maid
  Attempting uninstall: fsoft_maid
    Found existing installation: fsoft-maid 0.3.6
    Uninstalling fsoft-maid-0.3.6:
      Successfully uninstalled fsoft-maid-0.3.6
Successfully installed fsoft_maid-0.4.0
(base) murtaza@aa:~/dir/app$ maid -o output.md --maid-file maid.json src prisma 'next.config.ts' 'tsconfig.json' 
Traceback (most recent call last):
  File "/home/murtaza/miniconda3/bin/maid", line 5, in <module>
    from fsoft_maid import main
  File "/home/murtaza/miniconda3/lib/python3.12/site-packages/fsoft_maid.py", line 40, in <module>
    from lib.pattern_matcher import PatternMatcher
ModuleNotFoundError: No module named 'lib'
```
I tried uninstalling and reinstalling, as well as installing in a clean env. Still got the same error. 

I cloned the repo, asked claude to help me fix it and got it working. The following methods work now:
``` bash
maid -o output.md --pattern "src/app/legal/terms-of-service/page.tsx" --pattern "src/app/legal/privacy-policy/page.tsx" --pattern "src/app/legal/sla/page.tsx" src

maid -o output.md --pattern "src/app/legal/*/page.tsx" src
```
However, a maid.json file in the main directory doesn't do anything, with or without directly referencing it in the command:

``` bash
maid -o output.md src
maid -o output.md --maid-file maid.json src
```

I've tried with the following in the maid.json file:

``` json
{
  "patterns": [
    "**/legal/*/page.tsx"
  ],
  "rules": []
}

OR

{
  "patterns": [
    "**/legal/terms-of-service/**",
    "**/legal/privacy-policy/**",
    "**/legal/sla/**"
  ],
  "rules": []
}

OR 

{
  "patterns": [
    "src/app/legal/terms-of-service/page.tsx",
    "src/app/legal/privacy-policy/page.tsx",
    "src/app/legal/sla/page.tsx"
  ],
  "rules": []
}
```

**Comment by fsoft72** [comment]
Hello @murtaza-nasir   I have updated the package again. Now `0.4.2` should fix the lib import problem.
Please, try this new release.

If the problem persist, could you please provide me the complete file and folder structure of your app (just the file names and dirnames, not the content)?

**Comment by murtaza-nasir** [comment]
I can confirm the lib import problem is fixed. For the other issue, I can make do with the --patterns for now. My folder structure is as follows:

``` text
.
├── components.json
├── directory_structure.txt
├── logs
│   └── app.log
├── maid.json
├── next.config.ts
├── next-env.d.ts
├── output.md
├── package.json
├── package-lock.json
├── password-migration.log
├── pid.txt
├── postcss.config.mjs
├── prisma
│   ├── migrations
│   │   ├── 20241111064551_init_schema
│   │   │   └── migration.sql
│   │   ├── 20241119200743_add_email_verification
│   │   │   └── migration.sql
│   │   ├── 20241120001811_add_profile_data
│   │   │   └── migration.sql
│   │   ├── 20241120071614_add_user_types
│   │   │   └── migration.sql
│   │   └── migration_lock.toml
│   └── schema.prisma
├── public
│   ├── file.svg
│   ├── globe.svg
│   ├── logo.svg
│   ├── next.svg
│   ├── pdfix
│   ├── site.webmanifest
│   ├── vercel.svg
│   └── window.svg
├── README.md
├── scripts
│   └── migrate-passwords.ts
├── src
│   ├── app
│   │   ├── admin
│   │   │   ├── page.tsx
│   │   │   └── prompts
│   │   ├── api
│   │   │   ├── admin
│   │   │   │   └── users
│   │   │   │       └── route.ts
│   │   │   ├── auth
│   │   │   │   ├── [...nextauth]
│   │   │   │   │   └── route.ts
│   │   │   │   ├── resend-verification
│   │   │   │   │   └── route.ts
│   │   │   │   ├── signup
│   │   │   │   │   └── route.ts
│   │   │   │   └── verify
│   │   │   │       └── route.ts
│   │   │   ├── documents
│   │   │   │   └── to-markdown
│   │   │   │       └── route.ts
│   │   │   ├── generate-prompt
│   │   │   │   └── route.ts
│   │   │   ├── prompts
│   │   │   │   ├── check-duplicate
│   │   │   │   │   └── route.ts
│   │   │   │   ├── export
│   │   │   │   ├── [id]
│   │   │   │   │   └── route.ts
│   │   │   │   ├── import
│   │   │   │   ├── last-used
│   │   │   │   │   └── route.ts
│   │   │   │   └── route.ts
│   │   │   └── user
│   │   │       └── profile
│   │   │           └── route.ts
│   │   ├── auth
│   │   │   ├── signin
│   │   │   │   └── page.tsx
│   │   │   ├── signup
│   │   │   │   └── page.tsx
│   │   │   ├── verify
│   │   │   │   └── page.tsx
│   │   │   └── verify-email
│   │   │       └── page.tsx
│   │   ├── components
│   │   │   ├── auth
│   │   │   ├── AuthToggle.tsx
│   │   │   ├── VariousComponentsApp.tsx
│   │   │   ├── TextBox.tsx
│   │   │   ├── theme-provider.tsx
│   │   │   ├── theme-toggle.tsx
│   │   │   └── ui
│   │   │       ├── button.tsx
│   │   │       ├── card.tsx
│   │   │       ├── checkbox.tsx
│   │   │       ├── collapsible.tsx
│   │   │       ├── dialog.tsx
│   │   │       ├── dropdown-menu.tsx
│   │   │       ├── input.tsx
│   │   │       ├── label.tsx
│   │   │       ├── radio-group.tsx
│   │   │       ├── SavePromptDialog.tsx
│   │   │       ├── scroll-area.tsx
│   │   │       ├── sheet.tsx
│   │   │       ├── Sidebar.tsx
│   │   │       ├── switch.tsx
│   │   │       ├── table.tsx
│   │   │       ├── tabs.tsx
│   │   │       └── textarea.tsx
│   │   ├── favicon.ico
│   │   ├── fonts
│   │   │   ├── GeistMonoVF.woff
│   │   │   └── GeistVF.woff
│   │   ├── globals.css
│   │   ├── layout.tsx
│   │   ├── legal              <------------------------- Directories I want to skip.
│   │   │   ├── privacy-policy
│   │   │   │   └── page.tsx
│   │   │   ├── sla
│   │   │   │   └── page.tsx
│   │   │   └── terms-of-service
│   │   │       └── page.tsx
│   │   ├── logo.svg
│   │   ├── page.tsx
│   │   ├── profile
│   │   │   └── page.tsx
│   │   └── prompt-management
│   │       └── page.tsx
│   ├── lib
│   │   ├── api-client.ts
│   │   ├── auth.ts
│   │   ├── defaultPrompts.ts
│   │   ├── email.ts
│   │   ├── hover-settings.tsx
│   │   ├── json-parser.ts
│   │   ├── prisma.ts
│   │   ├── rateLimiter.ts
│   │   ├── utils.ts
│   │   └── variableUtils.ts
│   ├── middleware
│   ├── middleware.ts
│   └── types
│       ├── index.d.ts
│       ├── prompt.ts
│       └── textbox.ts
├── start.sh
├── status.sh
├── stop.sh
├── tailwind.config.ts
├── tsconfig.json
├── types
└── uploads

53 directories, 121 files
```

**Comment by fsoft72** [comment]
Thanks for the file structure, can you please create it again in this way:

- open a shell in the root of your project
- lunch this command:  `find . > folder-structure.txt`

and the attach the `folder-structure.txt` file here

**Comment by murtaza-nasir** [comment]
I have attached it here.

[folder-structure.txt](https://github.com/user-attachments/files/18238377/folder-structure.txt)

**Comment by fsoft72** [comment]
Thanks, but I gave you the wrong bash command :-(

Please, do it again with: 

`find . -type f > folder-structure.txt`

thanks

**Comment by murtaza-nasir** [comment]
I have attached it below. 

[folder-structure.txt](https://github.com/user-attachments/files/18239369/folder-structure.txt)

**Comment by fsoft72** [comment]
Hello @murtaza-nasir , I have just released new version `0.4.5` testing on your file structure.

The `maid.json` file I am using is this:

```json
{
        "patterns": [
                ".next",
                "./src/app/legal/**"
        ]
}
```

If you call `maid` with `--verbose`  option you can have a list of included and excluded files.

Hope this fix your issues :-)

Happy Xmas!

(and don't forget to :star: the project ;-) )

**Comment by murtaza-nasir** [comment]
Hello @fsoft72,

I updated and tried using the maid.json file you provided with an exact copy-paste, but it still doesn't work. In any case, I'm just gonna continue using it with the patterns switches.

Thank you for your help!

**Comment by fsoft72** [comment]
@murtaza-nasir  this is strange, since I am using exactly your filesystem structure.

Could you provide (from the root of your project and with the `maid.json` present):

- output of:   `maid . --verbose -o output.md >  maid-command.log`
- complete `maid.json` file 
- `find . -type f > file_system.txt`

So I can check

Thanks
